<a href="https://colab.research.google.com/github/helianakhjavani/Recommended-system/blob/main/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Library**

In [4]:
import numpy as np

In [2]:
w = [1,2,3]
print(w)
type(w)

[1, 2, 3]


list

In [6]:
a = np.array(w)
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [7]:
b = np.array([[1,2,3], [4,5,6]])
print(b)
type(b)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [8]:
c = np.array([[6,8,9],[4,2,9]])
print(b+c)

[[ 7 10 12]
 [ 8  7 15]]


**elementwise muiltiplication**

In [10]:
b * c

array([[ 6, 16, 27],
       [16, 10, 54]])

**dot method**

In [12]:
u = np.array([[1,0],[0,1]])
v = np.array([[4,1],[2,2]])

np.dot(u,v)

array([[4, 1],
       [2, 2]])

In [15]:
b / c

array([[0.16666667, 0.25      , 0.33333333],
       [1.        , 2.5       , 0.66666667]])

In [14]:
b % c

array([[1, 2, 3],
       [0, 1, 6]])

In [16]:
b == c

array([[False, False, False],
       [ True, False, False]])

**array_equal method**



In [17]:
np.array_equal(b,c)

False

In [18]:
np.zeros([3,5])     #we can use tuple instead of list

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**sort method**

In [19]:
q = np.array([[4,2],[3,1]])
np.sort(q)

array([[2, 4],
       [1, 3]])

In [21]:
np.sort(q, axis =0)     #axis = 0 sort column based. default axis =1

array([[3, 1],
       [4, 2]])

In [22]:
np.sort(q, axis = None)

array([1, 2, 3, 4])

**cumsum method**

In [24]:
q

array([[4, 2],
       [3, 1]])

In [23]:
np.cumsum(q)

array([ 4,  6,  9, 10])

In [25]:
np.cumsum(q, axis = 0)

array([[4, 2],
       [7, 3]])

In [26]:
np.cumsum(q, axis = 1)

array([[4, 6],
       [3, 4]])

In [27]:
np.cumsum(q, axis = None)

array([ 4,  6,  9, 10])

**cumprod method**

In [28]:
np.cumprod(q)

array([ 4,  8, 24, 24])

In [29]:
np.cumprod(q , axis = 0) 

array([[ 4,  2],
       [12,  2]])

In [30]:
np.cumprod(q , axis =1)

array([[4, 8],
       [3, 3]])

**ceil and floor methods**

In [33]:
m = np.array([2.6,4.6,5.8,10.7])
m

array([ 2.6,  4.6,  5.8, 10.7])

In [34]:
np.ceil(m)

array([ 3.,  5.,  6., 11.])

In [35]:
np.floor(m)

array([ 2.,  4.,  5., 10.])

**arrange method**

In [36]:
np.arange(2,14)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [37]:
np.arange(2,14,2)

array([ 2,  4,  6,  8, 10, 12])

**reshape method**

In [38]:
np.arange(2,14,2).reshape((2,3))

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [39]:
np.arange(2,14,2).reshape(-1,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])

In [40]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
a = np.arange(15).reshape(-1,1)

**shape method**

In [43]:
a.shape

(15, 1)

**linspace method**

In [45]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [47]:
np.linspace(0,1,100).reshape((10,10))

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

asarray method

In [48]:
x = [1,2,3]
print(x)
print(type(x), '\n')


y = np.asarray(x)
print(y)
print(type(y), '\n')

[1, 2, 3]
<class 'list'> 

[1 2 3]
<class 'numpy.ndarray'> 



In [49]:
c = np.array(x)
print(c)
print(type(c), '\n')

[1 2 3]
<class 'numpy.ndarray'> 



In [56]:
#example

#list : arg0 -> (1,2,3)   arg1 -> (4,5)

list1 = [(1,2,3), (4,5)]
print(list1)
print(type(list1), '\n')

array1 = np.asarray(list1)
print(array1)
print(type(array1), '\n')

[(1, 2, 3), (4, 5)]
<class 'list'> 

[(1, 2, 3) (4, 5)]
<class 'numpy.ndarray'> 



/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [57]:
o = np.array([-5.6j, 0.2j, 11, 1+2j])
o

array([-0.-5.6j,  0.+0.2j, 11.+0.j ,  1.+2.j ])

**real method**

In [59]:
np.real(o).reshape(-1,1)

array([[-0.],
       [ 0.],
       [11.],
       [ 1.]])

**imag method**

In [60]:
np.imag(o)

array([-5.6,  0.2,  0. ,  2. ])

**Linear Algebra**

**transpose method**

In [61]:
x = np.array([[1,2],[3,4]])
xprime = x.transpose()
xprime

array([[1, 3],
       [2, 4]])

In [67]:
#Example
x = np.arange(16).reshape(4,4)
print("final output:\n", x,"\n", x.transpose())

final output:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


**Trace** 

In [69]:
x.trace()

30